module Etudes
{
	interface Formation
	{
		readonly attribute string intitule;
		boolean equals(in Formation f);
	};
	typedef sequence<Formation> listFormations;
	
	interface Licence : Formation
	{};
	
	typedef sequence<Licence> listLicences;
	interface Master : Formation
	{
	};

	exception pasDiplomeException 
	{
		string nomEtudiant;
		string nomDiplome;
	};
	
	interface Proposition;
	
	exception prerequisDejaExistantException
	{
		Proposition proposition;
	};
	
	exception PropositionDoesNotExistException
	{
		Formation nonProposee;
	};
	
	exception EtudiantInconnuException
	{
		string numEtudiantInconnu;
		string nomUniversite;
	};
	
	exception NombreMaxDeVoeuxAtteintException
	{};
	
	exception formationDejaProposeeException
	{};
	
	exception diplomesDifferentsException 
	{
		string nomEtudiant;
		string nomDiplome;
		string nomEtudiantDiff;
	};
	
	exception EtudiantDejaInscritException
	{
		string numEtudiant;
	};
	
	exception EtudiantPasInscritException
	{
		string numEtudiant;
	};
	
	exception MotDePasseErroneException
	{
		string numEtudiant;
	};
	
	exception VoeuDejaCreeException
	{
		string numEtudiant;
		string idVoeu;
	};

	interface Resultat;
	interface Universite;
	interface Proposition
	{
		readonly attribute Universite proposant;
		readonly attribute Formation masterPropose;
		attribute listFormations prerequis;
		readonly attribute long nbPlaces;
		string getId();
	};
	
	interface Etudiant;
	typedef sequence<Etudiant> listEtudiant;
	typedef sequence<Proposition> listPropositions;
	interface Universite
	{
		readonly attribute string nom;
		attribute listPropositions listeDesPropositions;
		listEtudiant getEtudiants();
		Etudiant getEtudiantByNumero(in string numEtudiant);
		void inscrire(in Etudiant etudiant, in string motDePasse) raises (EtudiantInconnuException, EtudiantDejaInscritException);
		void connecter(in Etudiant numEtudiant, in string motDePasse) raises (EtudiantInconnuException, EtudiantPasInscritException, MotDePasseErroneException);
		Proposition getPropositionByFormation(in Formation _formation);
		listFormations getPrerequis(in Proposition p) raises (PropositionDoesNotExistException);
		oneway void creerProposition(in string intituleMaster, in listLicences _prerequis) raises (formationDejaProposeeException);
		oneway void majPrerequis(in Proposition p, in listLicences _nouveauxPrerequis) raises (PropositionDoesNotExistException);
		string getId();
		void classerVoeux();
	};
	
	typedef sequence<Universite> listUniversites;
	interface Rectorat
	{
		readonly attribute string nom;
		Etudiant getEtudiantByNumero(in string numEtudiant) raises (EtudiantInconnuException);
		void demanderConnexion(in Etudiant etudiant, in string motDePasse) raises (EtudiantInconnuException, EtudiantPasInscritException, MotDePasseErroneException);
		void demanderInscription(in Etudiant etudiant, in string motDePasse) raises (EtudiantInconnuException, EtudiantDejaInscritException);
		oneway void referencer(in Universite universiteConnecte);
		oneway void dereferencer(in Universite universiteDeconnecte);
		listUniversites getListUniversites();
		listFormations getAccreditationsByUniversite(in Universite _universite);
		listPropositions getPropositionByFormation(in Formation _formation);
		string getId();
		void validerCandidatures();
	};
	
	typedef sequence<Rectorat> listRectorats;
	interface Ministere
	{
		listFormations getListFormations();
		listRectorats getListRectorats();
		listPropositions getPropositionByFormation(in Formation _formation);
		oneway void referencer(in Rectorat nomRectoratConnecte);
		oneway void dereferencer(in Rectorat rectoratDeconnecte);
		
	};
	
	enum EtatsVoeu {initial,valide,nonValide,cloture,enAttente,accepte,OUI,NON,OUIMAIS,NONMAIS};
	interface Voeu
	{
		readonly attribute Proposition propositionCorrespondante;
		readonly attribute Etudiant etudiantCorrespondant;
		attribute long position;
		attribute EtatsVoeu etatVoeu;
		oneway void modifierEtatVoeu(in EtatsVoeu nouvelEtat);
		string getId();
		boolean classable();
	};
	
	interface Resultat
	{
		readonly attribute string codeObtention;
		readonly attribute float moyenne;
		readonly attribute long position;
	};
	
	typedef sequence<Voeu> listVoeux;
	typedef sequence<Resultat> listResultats;
	interface Etudiant
	{
		readonly attribute string numEtudiant;
		readonly attribute listResultats resultats;
		
		readonly attribute listVoeux listeVoeux;
		boolean estMeilleurQue(in Etudiant _aComparer) raises (diplomesDifferentsException);
		boolean ResultatsValideForProposition(in Proposition p);
		void addVoeuEtudiant(in Voeu voeuAAjouter) ;
		Universite getUniversite();
		float getMoyenneLicenceEtudiant();
	};
	
	interface UtilVoeux 
	{
		listVoeux getMeilleurePropositionByEtudiant(in Etudiant _etudiant);
		void soumettreVoeu(in Proposition _aSoumettre, in Etudiant _soumetteur, in long position) raises (NombreMaxDeVoeuxAtteintException,VoeuDejaCreeException);
		listVoeux getVoeuxByEtudiant(in Etudiant _etudiant);
		listVoeux getVoeuxByUniversite(in Universite _universite);
		listVoeux getVoeuxByRectorat(in Rectorat rectoratConcerne);
		listVoeux getVoeuxByProposition(in Proposition p);
		listVoeux ordonnerListeVoeux(in listVoeux listeAOrdonner);
	};
};
