module Etudes
{
	interface Formation
	{
		readonly attribute string intitule;
		boolean equals(in Formation f);
	};
	typedef sequence<Formation> listFormations;
	
	interface Licence : Formation
	{};
	
	typedef sequence<Licence> listLicences;
	interface Master : Formation
	{
	};

	exception pasDiplomeException 
	{
		string nomEtudiant;
		string nomDiplome;
	};
	
	exception PropositionDoesNotExistException
	{
		Formation nonProposee;
	};
	
	exception EtudiantInconnuException
	{
		string numEtudiantInconnu;
		string nomUniversite;
	};
	
	exception NombreMaxDeVoeuxAtteintException
	{};

	interface Resultat;
	interface Universite;
	interface Proposition
	{
		readonly attribute Universite universiteSource;
		readonly attribute Master masterPropose;
		readonly attribute listLicences prerequis;
		void addPrerequis(in Licence l);
	};
	
	interface Etudiant;
	typedef sequence<Etudiant> listEtudiant;
	interface Universite
	{
		listEtudiant getEtudiants();
		Etudiant getEtudiantByNumero(in string numEtudiant);
		void inscrire(in Etudiant etudiant, in string motDePasse) raises (EtudiantInconnuException);
		void connecter(in Etudiant numEtudiant, in string motDePasse) raises (EtudiantInconnuException);
		Proposition getPropositionByFormation(in Master _formation);
		listLicences getPrerequis(in Proposition p) raises (PropositionDoesNotExistException);
		oneway void creerProposition(in Master m, in listLicences _prerequis);
		oneway void majPrerequis(in Proposition p, in listLicences _nouveauxPrerequis,in Universite u);
		short getPositionEtudiant(in Etudiant _sujet, in Licence _formation) raises (pasDiplomeException);
		boolean checkLicenceEtudiant(in Etudiant e, in Licence l);
	};
	
	typedef sequence<Universite> listUniversites;
	typedef sequence<Proposition> listPropositions;
	interface Rectorat
	{
		Etudiant getEtudiantByNumero(in string numEtudiant);
		void demanderConnexion(in Etudiant etudiant, in string motDePasse) raises (EtudiantInconnuException);
		void demanderInscription(in Etudiant etudiant, in string motDePasse) raises (EtudiantInconnuException);
		listUniversites getListUniversites();
		listFormations getAccreditationsByUniversite(in Universite _universite);
		listPropositions getPropositionByFormation(in Master _formation);
	};
	
	typedef sequence<Rectorat> listRectorats;
	interface Ministere
	{
		listFormations getListFormations();
		listRectorats getListRectorats();
		listPropositions getPropositionByFormation(in Formation _formation);
	};

	exception diplomesDifferentsException 
	{
		string nomEtudiant;
		string nomDiplome;
		string nomEtudiantDiff;
	};
	
	exception EtudiantDejaInscritException
	{
		string numEtudiant;
	};

	interface Resultat
	{
		readonly attribute string codeObtention;
		readonly attribute float moyenne;
		readonly attribute short position;
	};
	
	interface Voeu
	{
		readonly attribute Proposition propositionCorrespondante;
		readonly attribute Etudiant etudiantCorrespondant;
		attribute short position;
		attribute string etatVoeu;
		oneway void reponseOUI();
		oneway void reponseOUIMAIS();
		oneway void reponseNONMAIS();
		oneway void reponseNON();
		oneway void accepterCandidature();
		oneway void refuserCandidature();

		oneway void majClassement(in short classement);
	};
	
	typedef sequence<Voeu> listVoeux;
	
	interface Etudiant
	{
		attribute Resultat resultats;
		readonly attribute listVoeux listeVoeux;
		boolean estMeilleurQue(in Etudiant _aComparer) raises (diplomesDifferentsException);
		short getPositionEtudiant();
		Universite getUniversite();
		void addVoeuEtudiant(in Voeu v) raises (NombreMaxDeVoeuxAtteintException);
		
		
	};
	
	interface UtilVoeux
	{
		listVoeux getMeilleurePropositionByEtudiant(in Etudiant _etudiant);
		oneway void soumettreVoeu(in Proposition _aSoumettre, in Etudiant _soumetteur, in short position) raises (NombreMaxDeVoeuxAtteintException);
		listVoeux getVoeuxByEtudiant(in Etudiant _etudiant);
		listVoeux getVoeuxByUniversite(in Universite _universite);
	};
};
